[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# [build.environment]
# API_KEY = "12345"

# [context.production.environment]
# API_KEY = "12345_prod"

# [context.deploy-preview.environment]
# API_KEY = "12345_preview"